### ISSUE TITLE
Suggestion to read about project structuring

### ISSUE THREAD

**Issue by MohamedAliRashad** [AymanNasser/Aroma#1]
There are different resources in something like this, for example
1. https://docs.python-guide.org/writing/structure/
2. https://dev.to/codemouse92/dead-simple-python-project-structure-and-imports-38c6

The part for testing is not important in our case so it can be skipped.

**Comment by AymanNasser** [comment]
Thanks rashad for initiating the first issue, we'll take it into our consideration
